### ISSUE TITLE
connection is not private

### ISSUE THREAD

**Issue by bgobi1991** [saasitive/django-react-boilerplate#24]
Hello Team,
I have issue when opening domain in browser. 
![image](https://github.com/saasitive/django-react-boilerplate/assets/9972138/b8146ba5-6dce-419f-af0c-4823fdffdd6e)

**Comment by pplonski** [comment]
Hi @bgobi1991, what address are you using? Looks like certificates are not valid, maybe not updated?

**Comment by bgobi1991** [comment]
> Hi @bgobi1991, what address are you using? Looks like certificates are not valid, maybe not updated?

Thanks. @pplonski . During letsencrypt generation i used staging=0. Now i changed this staging=1. now it's working fine.
