### ISSUE TITLE
typo error in tutorial 

### ISSUE THREAD

**Issue by moreaupascal56** [saasitive/django-react-boilerplate#3]
Hey Team :) First thanks a lot for the tutorial, 
I am at 4th step and just wanted to tell yoiu that there is a typo error in the tuto https://saasitive.com/tutorial/react-token-based-authentication-django/ 
![Capture](https://user-images.githubusercontent.com/50910271/107422361-34429580-6b1b-11eb-9afb-09b0959e8754.JPG)
in // frontend/src/components/SignupReducer.js there is subimted instead of submitted, i have no idea if this is important but that's it! 
Also I had to install history 4.10.1 instead of 5.0.0

**Comment by moreaupascal56** [comment]
btw I didn't know how to contact you other than github :)

**Comment by pplonski** [comment]
@moreaupascal56 thank you for reporting. Github is good place to report. With the next post I will fit this typo. Once again thank you!

**Comment by moreaupascal56** [comment]
No problem ! I've found another small one : in this step [django-rest-framework-email-verification](https://saasitive.com/tutorial/django-rest-framework-email-verification/). 
In the tests part when you are adding the 3 tests about re-sending the verification email : there is no mention that you should add the line `    resend_verification_url = '/api/v1/users/resend_activation/'
 ` in the `#endpoints needed` part, therefore the tests are failing at first. 
 Anyway that is quite logical that we need this line but I still report it 👍 
![Capture](https://user-images.githubusercontent.com/50910271/107849367-1adf6900-6dfb-11eb-98a1-bd64f8e76b26.JPG)

Once again the tuto is really well done it really makes understand well what we are doing 🥇
