### ISSUE TITLE
Service 'nginx' failed to build : COPY failed: stat /var/lib/docker/tmp/docker-builder996262710/frontend/package.json: no such file or directory

### ISSUE THREAD

**Issue by Avin-Techv** [saasitive/django-react-boilerplate#6]
I am following the tutorial https://saasitive.com/tutorial/docker-compose-django-react-nginx-let-s-encrypt/ step by step but I get this error saying no file found but the file mentioned is correctly in place

**Comment by pplonski** [comment]
Please double check the file structure and try to build fresh docker image

**Comment by pplonski** [comment]
What it was?

**Comment by Avin-Techv** [comment]
I rechecked the same issue persists

**Comment by Avin-Techv** [comment]
I redid the entire thing, now this issue does not exist
