### ISSUE TITLE
After running my project the backend part renders a django admin page without the static files

### ISSUE THREAD

**Issue by Avin-Techv** [saasitive/django-react-boilerplate#8]
After running my project the backend part renders a django admin page without the static files like this
![issue_backend](https://user-images.githubusercontent.com/38907984/110581475-a2b55a80-8190-11eb-95d6-a79bf2bc161c.png)

**Comment by pplonski** [comment]
Please try to load in fresh browser, maybe clear the cache or try different web browser. It should work. Please check example deployment: https://boilerplate.saasitive.com/admin

**Comment by Avin-Techv** [comment]
Since the frontend was rendering correctly I put the static files into the folder **/usr/share/nginx/html/** now it works correctly
